CI: Start uploading Electron-next binaries to their own repo (#1119)
* CI: Start uploading Electron-next binaries to their own repo

Similar to the setup for Rolling. So we can get these bins out there,
for testing and such, getting the word out, etc.

* CI: Build using yarn dist --next (rather than without the --next flag)

Want to build "-next" bins, not vanilla Pulsar bins.

* CI: Checkout submodules before editor tests

Ensure ppm is present so yarn dist ppm check doesn't warn

* electron-builder: Restore "warningsAsErrors: false" to the new electron-builder config file

We get the following, otherwise, it would seem:

  warning 6010: install function "EnvVarUpdate" not referenced - zeroing code (179-395) out

followed by:

  Error: warning treated as error

And then electron-builder exits with that as the error status.
So, I suppose we want to avoid that.

* CI: Checkout ppm submodule for package tests too

Again so that the "yarn dist" command won't warn and exit.

* CI: Run editor and package tests on push to 'updated-latest-electron' branch