cirrus: Install python setuptools with brew, not pip
Doing this with pip gives an error message, for some reason.

```
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
```

So, getting this package from brew instead of pip should fix the error