Cirrus: Don't try to uninstall already not installed node@20 package
This used to come preinstalled in Cirrus's base CI image, and caused us
some problems before, so we uninstalled it. Now, with this Node package
version being deprecated in Homebrew, it is no-longer preinstalled in
Cirrus' base CI image, so we don't have to uninstall it manually!

Also, trying to uninstall this when it wasn't already installed was
causing an error:

```
brew uninstall node@20
Error: No such keg: /opt/homebrew/Cellar/node@20
```

(Avoid CI-run-breaking errors with this one weird trick!)